### ISSUE TITLE
chart rig-operator: generate certificates for webhooks

### ISSUE THREAD

**Issue by blacksails** [rigdev/rig#661]
The rig-operator cli has been extended with a command for certificate generation. This can be used in helm pre/post hooks to setup the certificate for the CRD webhook.

TODO:
- [x] Command to be run as a helm post-install job to verify that the rig-operator api is ready, before proceeding #667 
- [x] Add option of patching CRDs. Currently we only patch the `*WebhookConfiguration` objects which means that we dont register the CA for the conversion webhook (this is registered on the CRD resource. #670
- [x] Add apicheck post-install hook. This will ensure that the APIs provided by rig-operator are ready for use. #671
- [x] Add helm pre-install hook for generating certificates #679 
- [x] Add helm post-install hook for patching webhook configuration with CA certificate #679
