### ISSUE TITLE
Introduce k8s CRD/Operator for Capsules

### ISSUE THREAD

**Issue by andersjohnsen** [rigdev/rig#95]
This issue will be an ongoing tracking issue with regards to what is missing on the Capsule operator implementation.

- [x]  Add webhook config to helm chart #111
- [x]  Add validation for file mounting config #96
- [x]  Figure out how to use the rig logger with the improvements from controller-runtime as the controller-runtime logger
- [x]  Check for loadbalancer resource ownership in test #100
- [x]  Simplify folder path for integration test #102 
- [x]  Add integration test for webhooks #127 
- [x]  Add cluster.Gateway implementation which uses CRD #91 
- [ ] #176
- [x]  Add Capabilities API #173 
- [x] Run integration tests in CI #101 
- [x] Make standalone binary #134 
- [x] Setup goreleaser for releases of operator #135 
- [x] Make helmchart for deployment #152 
- [x] Certificates are not auto-created when TLS is enabled #158 
- [x] Config files are not mounted #156

**Comment by blacksails** [comment]
Added an issue for health probe support
